# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from membrain.proto import memory_a2a_pb2 as memory__a2a__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_a2a_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryUnitStub(object):
    """The Neuromorphic Memory Unit service
    Provides associative memory operations for LLM agents
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Remember = channel.unary_unary(
                '/memory_bridge.MemoryUnit/Remember',
                request_serializer=memory__a2a__pb2.MemoryPacket.SerializeToString,
                response_deserializer=memory__a2a__pb2.Ack.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/memory_bridge.MemoryUnit/Recall',
                request_serializer=memory__a2a__pb2.QueryPacket.SerializeToString,
                response_deserializer=memory__a2a__pb2.ContextResponse.FromString,
                _registered_method=True)
        self.Consolidate = channel.unary_unary(
                '/memory_bridge.MemoryUnit/Consolidate',
                request_serializer=memory__a2a__pb2.SleepSignal.SerializeToString,
                response_deserializer=memory__a2a__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/memory_bridge.MemoryUnit/Ping',
                request_serializer=memory__a2a__pb2.Empty.SerializeToString,
                response_deserializer=memory__a2a__pb2.Ack.FromString,
                _registered_method=True)


class MemoryUnitServicer(object):
    """The Neuromorphic Memory Unit service
    Provides associative memory operations for LLM agents
    """

    def Remember(self, request, context):
        """Store a context vector with learning enabled
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Query for associated memories via pattern completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consolidate(self, request, context):
        """Trigger sleep phase for memory consolidation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryUnitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=memory__a2a__pb2.MemoryPacket.FromString,
                    response_serializer=memory__a2a__pb2.Ack.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=memory__a2a__pb2.QueryPacket.FromString,
                    response_serializer=memory__a2a__pb2.ContextResponse.SerializeToString,
            ),
            'Consolidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Consolidate,
                    request_deserializer=memory__a2a__pb2.SleepSignal.FromString,
                    response_serializer=memory__a2a__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=memory__a2a__pb2.Empty.FromString,
                    response_serializer=memory__a2a__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory_bridge.MemoryUnit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory_bridge.MemoryUnit', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryUnit(object):
    """The Neuromorphic Memory Unit service
    Provides associative memory operations for LLM agents
    """

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_bridge.MemoryUnit/Remember',
            memory__a2a__pb2.MemoryPacket.SerializeToString,
            memory__a2a__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_bridge.MemoryUnit/Recall',
            memory__a2a__pb2.QueryPacket.SerializeToString,
            memory__a2a__pb2.ContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consolidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_bridge.MemoryUnit/Consolidate',
            memory__a2a__pb2.SleepSignal.SerializeToString,
            memory__a2a__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory_bridge.MemoryUnit/Ping',
            memory__a2a__pb2.Empty.SerializeToString,
            memory__a2a__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
